### ISSUE TITLE
zos_job_submit generates NotADirectoryError: [Errno 135] EDC5135I Not a directory.: 'locale'

### ISSUE THREAD

**Issue by corytx69** [IBM/z_ansible_collections_samples#122]
Running latest zos ansible core.   Having issues getting zos_job_submit to submit JCL.  

Other modules such as zos_data_set, zos_operator and zos_job_output are working fine.    I attempted with and without quotes around src:

---
- hosts: zos_host
  collections:
    - ibm.ibm_zos_core
  gather_facts: no

  environment: "{{ environment_vars }}"

  tasks:

    - name: Submit the JCL
      zos_job_submit:
        src: "KZANSBL.SYSK.JCLLIB(WAIT)"
        location: DATA_SET
        wait: true
      register: response

Regardless of any type of job submit, the  EDC5135I Not a directory.: 'locale'  is the only error I see in the playbook output.

Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/u/kzansbl/python/usr/lpp/IBM/cyp/v3r9/pyz/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/u/kzansbl/python/usr/lpp/IBM/cyp/v3r9/pyz/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/u/kzansbl/python/usr/lpp/IBM/cyp/v3r9/pyz/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_ibm.ibm_zos_core.zos_job_submit_payload_mc6nq6it/ansible_ibm.ibm_zos_core.zos_job_submit_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_job_submit.py", line 816, in <module>
  File "/tmp/ansible_ibm.ibm_zos_core.zos_job_submit_payload_mc6nq6it/ansible_ibm.ibm_zos_core.zos_job_submit_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_job_submit.py", line 812, in main
  File "/tmp/ansible_ibm.ibm_zos_core.zos_job_submit_payload_mc6nq6it/ansible_ibm.ibm_zos_core.zos_job_submit_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_job_submit.py", line 647, in run_module
  File "/tmp/ansible_ibm.ibm_zos_core.zos_job_submit_payload_mc6nq6it/ansible_ibm.ibm_zos_core.zos_job_submit_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/module_utils/encode.py", line 65, in get_default_system_charset
  File "/tmp/ansible_ibm.ibm_zos_core.zos_job_submit_payload_mc6nq6it/ansible_ibm.ibm_zos_core.zos_job_submit_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/module_utils/system.py", line 119, in run_command
  File "/u/kzansbl/python/usr/lpp/IBM/cyp/v3r9/pyz/lib/python3.9/subprocess.py", line 956, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/u/kzansbl/python/usr/lpp/IBM/cyp/v3r9/pyz/lib/python3.9/subprocess.py", line 1828, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
NotADirectoryError: [Errno 135] EDC5135I Not a directory.: 'locale'

**Comment by ddimatos** [comment]
@corytx69 - I apologize for the delay, team has been extremely busy on some long term enhancements. If you are still watching this, what it appears to me to be doing is that it trying to figure out your systems locale to know what encoding to use. 

On or about where it fails, in USS it runs this command `locale -c charmap`, on my system I get
```
DDIMATO:/u/ddimato #>locale -c charmap
IBM-1047
```

If you could share the results of that command, it might help us identify a case where this command is not available or possibly some other reason. 

I would suggest as a work around, you set the encodings yourself to avoid the auto detection (running the locale command) , you can set the encoding for the submit module by adding this to the zos_job_submit` module. 

```
    encoding:
      from: ISO8859-1
      to: IBM-037
```

**Comment by ddimatos** [comment]
@corytx69 - going to close this out since there has been no updates on the suggestion above about running the `locale` command. If you are able to, feel free to reopen this case but it really does hinge on why `locale` was not available and on all our systems that is not the case. I have reached out to the `USS` experts in  parallel to understand if its possible the command is not a default utility or can be limited by ACL/Security permissions. 

In the future, issues related to a module should be opened in their respective repositories, you can visit galaxy and view each collections Git repo to know where to open an issue if you are unsure. For this particular module, the collection can be found in this [repository](https://github.com/ansible-collections/ibm_zos_core/issues).

Reopen if you are able to continue assisting. Thank you.

**Comment by ddimatos** [comment]
One more update, got a message back from the USS development, `locale` is a standard utility that is included with USS, thus it could be that your PATH is not defined with where to find `locale`, the standard sample we provide includes the most common locations for executibles, you can see that information [here](https://github.com/IBM/z_ansible_collections_samples/blob/master/docs/share/zos_core/configuration_guide.md#group-variables). Ansible does not honor your `.profile` if you have one on the managed node, it uses the environment vars we have outlined in the shared link.
